### ISSUE TITLE
filter, sort, weight and some other typesense search options have not been implemented yet?

### ISSUE THREAD

**Issue by fireindark707** [jaeyson/ex_typesense#1]
I would like to know if this is a work in progress? Or am I not finding the right code.

**Comment by jaeyson** [comment]
Hi @fireindark707  👋 it's still WIP. If you have something in mind and want to add, feel free to PR. Thank you for asking.

**Comment by jaeyson** [comment]
hi @fireindark707, i've bumped the version to include filter and sort (see the recent version). LMK if this helps.
