### ISSUE TITLE
Request to Release Latest Changes

### ISSUE THREAD

**Issue by njausteve** [jaeyson/ex_typesense#55]
Hey @jaeyson Would be possible to release the latest changes from the repository. 
There have been a few updates merged recently that would be beneficial to have available in the latest version. Thanks

**Comment by jaeyson** [comment]
@njausteve thanks for the nudge, will do 👌🏾

**Comment by njausteve** [comment]
Thanks @jaeyson for the releases.

**Comment by njausteve** [comment]
0.7.0 and 0.71 release
